export function cn(...classes) {
  return classes.flat().filter(Boolean).join(' ');
}

export const tw = {
  page: 'relative mx-auto w-full max-w-7xl px-4 py-8 sm:px-6 lg:px-8',
  pageWide: 'relative mx-auto w-full max-w-[1480px] px-4 py-8 sm:px-6 lg:px-8',
  pageShell: 'relative isolate overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel)] shadow-[var(--shadow)] backdrop-blur-xl',
  pageHeader: 'relative overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[linear-gradient(135deg,var(--surface-strong),var(--page-soft))] p-5 shadow-[var(--shadow)] sm:p-7',
  section: 'relative overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel)] p-5 shadow-[var(--shadow-sm)] sm:p-7',
  glass: 'relative isolate overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel)] shadow-[var(--shadow)] backdrop-blur-xl',
  glassSoft: 'relative isolate overflow-hidden rounded-[1.35rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] shadow-[var(--shadow-sm)] backdrop-blur-xl',
  card: 'group relative isolate overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-5 shadow-[var(--shadow-sm)] transition-all duration-300 ease-out hover:-translate-y-1 hover:border-[var(--accent-line)] hover:shadow-[var(--shadow)] active:scale-[0.99]',
  cardCompact: 'relative isolate overflow-hidden rounded-[1.25rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-4 shadow-[var(--shadow-sm)] transition-all duration-200 ease-out',
  cardInteractive: 'group relative isolate overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-5 shadow-[var(--shadow-sm)] transition-all duration-300 ease-out hover:-translate-y-1 hover:border-[var(--accent-line)] hover:shadow-[var(--shadow)] active:scale-[0.985]',
  hero: 'relative isolate grid min-h-[min(720px,calc(100vh-118px))] items-center gap-8 overflow-hidden rounded-[1.8rem] border border-[var(--line)] bg-[radial-gradient(circle_at_14%_12%,color-mix(in_srgb,var(--accent),transparent_68%),transparent_28rem),radial-gradient(circle_at_86%_12%,color-mix(in_srgb,var(--blue),transparent_84%),transparent_24rem),linear-gradient(135deg,var(--surface-strong),var(--page-soft))] p-6 shadow-[var(--shadow-lg)] md:grid-cols-[1.03fr_0.97fr] md:p-10 lg:p-12',
  eyebrow: 'text-[0.76rem] font-semibold uppercase tracking-[0.08em] text-[var(--accent-strong)]',
  title: 'font-semibold leading-[0.98] tracking-normal text-[clamp(2.7rem,7.2vw,6.6rem)] text-[var(--text)]',
  heading: 'font-semibold leading-[1.04] tracking-normal text-[clamp(2rem,4.6vw,3.8rem)] text-[var(--text)]',
  subcopy: 'max-w-2xl text-base leading-7 text-[var(--text-soft)] sm:text-lg',
  buttonPrimary: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[color-mix(in_srgb,var(--accent-strong),transparent_50%)] bg-[var(--accent-strong)] px-5 py-3 font-semibold text-[var(--accent-foreground)] shadow-[var(--glow)] transition-all duration-200 ease-out hover:-translate-y-0.5 hover:bg-[var(--accent)] active:scale-[0.98] focus-visible:ring-4 focus-visible:ring-[color-mix(in_srgb,var(--blue),transparent_72%)] disabled:pointer-events-none disabled:opacity-55',
  buttonGhost: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[var(--line)] bg-[var(--surface-panel-soft)] px-5 py-3 font-semibold text-[var(--text)] shadow-[var(--shadow-sm)] transition-all duration-200 ease-out hover:-translate-y-0.5 hover:border-[var(--accent-line)] hover:bg-[var(--accent-soft)] active:scale-[0.98] focus-visible:ring-4 focus-visible:ring-[color-mix(in_srgb,var(--blue),transparent_72%)] disabled:pointer-events-none disabled:opacity-55',
  buttonSoft: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[var(--line)] bg-[var(--accent-soft)] px-5 py-3 font-semibold text-[var(--text)] shadow-[var(--shadow-sm)] transition-all duration-200 ease-out hover:-translate-y-0.5 hover:border-[var(--accent-line)] active:scale-[0.98] disabled:pointer-events-none disabled:opacity-55',
  dangerButton: 'inline-flex min-h-11 items-center justify-center gap-2 rounded-full border border-[color-mix(in_srgb,var(--danger),transparent_62%)] bg-[color-mix(in_srgb,var(--danger),transparent_90%)] px-5 py-3 font-semibold text-[var(--danger)] shadow-[var(--shadow-sm)] transition-all duration-200 ease-out hover:-translate-y-0.5 active:scale-[0.98]',
  iconButton: 'inline-flex min-h-11 min-w-11 items-center justify-center rounded-full border border-[var(--line)] bg-[var(--surface-panel-soft)] text-[var(--text)] shadow-[var(--shadow-sm)] transition-all duration-200 hover:-translate-y-0.5 hover:border-[var(--accent-line)] active:scale-[0.96]',
  pill: 'inline-flex min-h-8 items-center justify-center gap-1.5 rounded-full border border-[var(--line)] bg-[var(--surface-panel-soft)] px-3 py-1 text-[0.72rem] font-semibold text-[var(--text-soft)]',
  input: 'w-full rounded-[1rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] px-4 py-3 text-[var(--text)] shadow-sm outline-none transition-all duration-200 placeholder:text-[var(--faint)] focus:border-[var(--accent-line)] focus:bg-[var(--surface-strong)] focus:ring-4 focus:ring-[color-mix(in_srgb,var(--blue),transparent_82%)]',
  textarea: 'w-full min-h-[132px] resize-y rounded-[1rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] px-4 py-3 text-[var(--text)] shadow-sm outline-none transition-all duration-200 placeholder:text-[var(--faint)] focus:border-[var(--accent-line)] focus:bg-[var(--surface-strong)] focus:ring-4 focus:ring-[color-mix(in_srgb,var(--blue),transparent_82%)]',
  fieldLabel: 'grid gap-2 text-sm font-semibold text-[var(--text)]',
  gridCards: 'grid gap-4 sm:grid-cols-2 xl:grid-cols-3',
  roomGrid: 'grid gap-5 sm:grid-cols-2 xl:grid-cols-3',
  dashboardGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
  emptyState: 'relative mx-auto grid max-w-xl justify-items-center gap-3 rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-8 text-center shadow-[var(--shadow-sm)]',
  skeleton: 'relative overflow-hidden rounded-[1.35rem] border border-[var(--line)] bg-[var(--surface-inset)] shadow-[var(--shadow-sm)]',
  chatShell: 'relative mx-auto grid min-h-[calc(100vh-92px)] w-full max-w-[1540px] gap-4 px-3 pb-4 sm:px-5 lg:grid-cols-[minmax(0,1fr)_384px] lg:px-7',
  chatPanel: 'relative isolate flex min-h-[calc(100vh-112px)] min-w-0 flex-col overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel)] shadow-[var(--shadow)] backdrop-blur-xl',
  chatHeader: 'sticky top-0 z-20 flex flex-col gap-4 border-b border-[var(--line)] bg-[var(--surface-panel)] px-4 py-4 backdrop-blur-xl sm:px-5 lg:flex-row lg:items-center lg:justify-between',
  messageList: 'relative flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto px-3 py-4 sm:px-5 lg:px-6',
  composer: 'sticky bottom-0 z-20 border-t border-[var(--line)] bg-[color-mix(in_srgb,var(--surface-strong),transparent_3%)] p-3 shadow-[0_-24px_70px_rgba(0,0,0,0.09)] backdrop-blur-2xl sm:p-4',
  drawer: 'fixed inset-y-0 right-0 z-40 w-[min(94vw,430px)] overflow-y-auto border-l border-[var(--line)] bg-[var(--surface-panel)] p-4 shadow-[var(--shadow-lg)] backdrop-blur-xl transition-transform duration-300 ease-out lg:static lg:z-auto lg:w-auto lg:rounded-[1.6rem] lg:border lg:p-4',
  drawerSection: 'relative overflow-hidden rounded-[1.35rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-5 shadow-[var(--shadow-sm)]',
  messageBubbleMine: 'max-w-[min(78vw,720px)] rounded-[1.35rem] border border-[color-mix(in_srgb,var(--accent-strong),transparent_72%)] bg-[color-mix(in_srgb,var(--accent),transparent_84%)] px-4 py-3 shadow-[var(--shadow-sm)]',
  messageBubbleOther: 'max-w-[min(78vw,720px)] rounded-[1.35rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] px-4 py-3 shadow-[var(--shadow-sm)]',
  messageBubbleSystem: 'mx-auto inline-flex max-w-[82%] items-center gap-2 rounded-full border border-[var(--line)] bg-[var(--surface-inset)] px-4 py-2 text-sm font-bold text-[var(--text-soft)] shadow-[var(--shadow-sm)]',
  actionMenu: 'rounded-[1.15rem] border border-[var(--line)] bg-[var(--surface-strong)] p-2 shadow-[var(--shadow)] backdrop-blur-2xl',
  notificationCard: 'relative overflow-hidden rounded-[1.35rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-4 shadow-[var(--shadow-sm)] transition-all duration-200 hover:-translate-y-0.5',
  adminCard: 'relative overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-5 shadow-[var(--shadow-sm)]',
  pricingCard: 'relative isolate overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-5 shadow-[var(--shadow)] transition-all duration-300 hover:-translate-y-1',
  storeCard: 'relative isolate overflow-hidden rounded-[1.6rem] border border-[var(--line)] bg-[var(--surface-panel-soft)] p-5 shadow-[var(--shadow-sm)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[var(--shadow)]',
};
